Waiting for mongo connectino

diff --git a/.github/workflows/rubyonrails.yml b/.github/workflows/rubyonrails.yml
--- a/.github/workflows/rubyonrails.yml
+++ b/.github/workflows/rubyonrails.yml
@@ -34,6 +34,14 @@ jobs:
         uses: ruby/setup-ruby@v1
         with:
           bundler-cache: true
+      - name: Wait for MongoDB
+        run: |
+            for i in {1..10}; do
+              nc -z localhost 27017 && echo "MongoDB is ready!" && exit 0
+              echo "Waiting for MongoDB..."
+              sleep 3
+            done
+            echo "MongoDB failed to start" && exit 1
       - name: Prepare MongoDB configuration
         run: |
           echo "MONGO_USERNAME=socialconnectTest" >> .env
